configuration:  
  projectName: selfregistration
---
spring:  
  profiles: development
server:  
  port: 8080
application:
  checkPersonInGMMRestServiceUri : "checkPerson/%s/%s/%s/%s"
  searchPersonsRestServiceUri : "search"
  personsListRestServiceUri : "list/%s"
---
spring:  
  profiles: localhost
server:  
  port: 8080
message:
  greeting: Hello from the configuration - This is localhost Env't Changed Value!  
application:
  checkPersonInGMMRestServiceUri : "checkPerson/%s/%s/%s/%s"
  searchPersonsRestServiceUri : "search"
  personsListRestServiceUri : "list/%s"
